packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@sentry/cli': true
  '@firebase/util': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
engineStrict: true
