export type DisclaimerParagraph = { text: string };

export const DISCLAIMER_TITLE = 'Confidentiality and Restricted Use Notice';

export const EN_SECTION = 'English';

export const DISCLAIMER_EN_PARAGRAPHS: DisclaimerParagraph[] = [
  {
    text: 'This report is generated by PT. Eagle Protect Security for the named client and site only. It may contain confidential security information, site information, employee information, photos, GPS coordinates, timestamps, system logs, and other operational records.',
  },
  {
    text: 'This report is provided only for security operations, verification, incident review, internal client records, service accountability, and authorized legal or regulatory purposes. It must not be copied, forwarded, published, uploaded to social media, disclosed to unauthorized persons, altered, or used for any purpose outside the security service relationship without written approval from PT. Eagle Protect Security, except where disclosure is required by law or by an authorized government, court, or legal authority.',
  },
  {
    text: 'The report format, generated records, timestamps, location records, system logs, and operational documentation are confidential records of PT. Eagle Protect Security. Any unauthorized access, copying, alteration, distribution, leakage, or misuse of this report may result in contractual, civil, administrative, and/or criminal consequences under applicable laws and regulations of the Republic of Indonesia.',
  },
  {
    text: 'If you received this report by mistake, please notify PT. Eagle Protect Security immediately, do not copy or share it, and delete it from your device.',
  },
];

export const ID_SECTION = 'Bahasa Indonesia';

export const DISCLAIMER_ID_PARAGRAPHS: DisclaimerParagraph[] = [
  {
    text: 'Laporan ini dibuat oleh PT. Eagle Protect Security hanya untuk klien dan lokasi yang tercantum di dalam laporan ini. Laporan ini dapat berisi informasi keamanan yang bersifat rahasia, informasi lokasi, informasi karyawan, foto, koordinat GPS, waktu kejadian, log sistem, dan catatan operasional lainnya.',
  },
  {
    text: 'Laporan ini hanya boleh digunakan untuk keperluan operasional keamanan, verifikasi, peninjauan insiden, arsip internal klien, pertanggungjawaban layanan, serta keperluan hukum atau regulasi yang sah. Laporan ini tidak boleh disalin, diteruskan, dipublikasikan, diunggah ke media sosial, diberikan kepada pihak yang tidak berwenang, diubah, atau digunakan untuk tujuan di luar hubungan layanan keamanan tanpa persetujuan tertulis dari PT. Eagle Protect Security, kecuali apabila diwajibkan oleh hukum atau diminta oleh pemerintah, pengadilan, atau otoritas hukum yang berwenang.',
  },
  {
    text: 'Format laporan, data yang dihasilkan sistem, waktu pencatatan, catatan lokasi, log sistem, dan dokumentasi operasional merupakan catatan rahasia milik PT. Eagle Protect Security. Setiap akses, penyalian, perubahan, penyebaran, kebocoran, atau penyalahgunaan laporan ini tanpa izin dapat menimbulkan konsekuensi kontraktual, perdata, administratif, dan/atau pidana sesuai dengan peraturan perundang-undangan yang berlaku di Republik Indonesia.',
  },
  {
    text: 'Apabila Anda menerima laporan ini secara tidak sengaja, harap segera menghubungi PT. Eagle Protect Security, jangan menyalin atau membagikan laporan ini, dan hapus laporan ini dari perangkat Anda.',
  },
];
